### ISSUE TITLE
Separate bongocat keymap

### ISSUE THREAD

**Issue by kimisgold** [foureight84/sofle-keyboard-pimoroni#2]
I was really happy to find your bongocat animation, and admittedly don't use the pimoroni. Would you be open to separating out an updated keymap of the bongocat with via support? I've been trying to modify it for myself but keep running into quirks. Making the original VIA-compatible has suddenly lost me right encoder functionality, and trying to port the animation over to the current VIA keymap has broken the animation.

**Comment by foureight84** [comment]
@kimisgold I've made a separate branch without the Pimoroni trackball but with VIA and bongo cat added. https://github.com/foureight84/qmk_firmware/tree/sofle_foureight84_bongo_no_trackball

Give it a try and let me know how it works out

**Comment by kimisgold** [comment]
Thank you so much! It works great, and I really appreciate your quick response.

**Comment by foureight84** [comment]
@kimisgold you're welcome
