### ISSUE TITLE
Trackball - defective, incompatible, or did I do something wrong?

### ISSUE THREAD

**Issue by Moghul** [foureight84/sofle-keyboard-pimoroni#4]
Hi, I tried to use your solution to add the Pimoroni trackball to a Sofle V2. I made an issue here and asked what the appropriate pins on the controller would be: https://github.com/josefadamcik/SofleKeyboard/issues/161

After soldering and flashing everything, I managed to get everything else working, but the Pimoroni Trackball doesn't work as I expected it. The trackball does seem to detect some signals, but mostly it just wiggles around the same spot and sometimes it jumps across the screen here and there. 

I haven't touched the code you wrote for the trackball and I do believe it's soldered to the right pins. What information could I give you to help troubleshoot it? My C skills are rudimentary at best and limited right now to writing keymaps.

I do already plan on ordering a replacement in case the item itself was defective but I wanted your take on it just in case. Should I take it apart in case it's dirty or something?

**Comment by foureight84** [comment]
Are you using the QMK master branch by chance? My keymap has been merged into the main branch, I would use that. If you are using my local branch (out of sync with qmk master) then you have to use it as is and not try to merge with qmk master. There's been a lot of changes to the master branch that the old code would need to change (that's already addressed in the master branch).

Also, someone did verify that the pins are still available on the Sofle V2 https://www.reddit.com/r/ErgoMechKeyboards/comments/o3zwgn/sofle_v21_rgb_pcb_with_trackball/

**Comment by Moghul** [comment]
I'm using your repo and branch here as it is. It took some finagling to get Pillow to be installed on my windows machine though. 
Yup, I am also in that reddit thread talking to people, I'm the guy trying to make it work on a 2.0, not a 2.1
I guess I'll try to take this trackball apart and see if it's dirty and I'll also buy another one.

**Comment by foureight84** [comment]
You could try connecting the trackball to the left (master side) first and see if that changes and switch to using the QMK repo master branch instead of my forked repo of the older version.

**Comment by Moghul** [comment]
Resoldering the trackball is a bit more effort than I have time for this week, but how would I use the master repo? Switch to it, and copy/paste your keymaps directory? I've already tried that and I was getting a ton of code related errors. Something about warnings counting as errors.

I wasn't using your commands though, I was using the ones on QMK's docs, perhaps that was it. I think I'll have time again next week... Fingers crossed. Thanks a ton for the help, I promise to come back with an update.

**Comment by foureight84** [comment]
Just switch to the master repo and use the same flash commands for my keymap. My keymap was merged into the official repo a few months ago.
